spring:
  datasource:
    url: jdbc:postgresql://krb5.local/postgres
logging:
  level:
    root: INFO # DEBUG
    ua.com.pragmasoft: DEBUG
app:
  security:
    kerberos:
      service-principal: HTTP/krb5.local # MUST be HTTP/<full qualified domain name of the web server domain>
      keytab-location: http.keytab # relative to the current directory cwd
      spnego-entrypoint: /spnego.html
  